version: "3.8"
   
services:
  cabifydb:
    container_name: cabifydb
    image: mysql:5.7 
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: cabifydb
        MYSQL_DATABASE: cabifydb
        MYSQL_USER: cabifydb
        MYSQL_PASSWORD: cabifydb
  web1:
    build: .
    container_name: django-server0
    command: python3 Carpooling/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/server
    ports:
      - 1111:8000
    depends_on:
      - cabifydb
  
  web2:
    build: .
    container_name: django-server1
    command: python3 Carpooling/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/server
    ports:
      - 2222:8000
    depends_on:
      - cabifydb

  web3:
    build: .
    container_name: django-server2
    command: python3 Carpooling/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/server
    ports:
      - 3333:8000
    depends_on:
      - cabifydb
    
  nginx:
    image: nginx:1.17.10
    container_name: loadbalancer
    ports:
      - 8000:80
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - web1
      - web2
      - web3